reference_jdk: &reference_jdk
  'JDK="adopt@1.8"'
  
reference_build: &reference_build
  os: linux
  env: *reference_jdk

language: minimal

os:
  - osx
  - windows
  - *reference_os
  
stages:
  - base
  - test
    
env:
  global:
    # Convenience variables for shortening commands
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.8"
    - JDK="adopt@1.11"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt@"
    - JDK="adopt-openj9@"

before_install:
    - chmod +x gradlew
    # Check out the script set
    - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
    # Install the JDK you configured in the $JDK environment variable
    # Never use travis_retry: hides failures. travis_retry is used internally where possible.
    - source $GRAVIS/install-jdk
    
before_cache:
  - $GRAVIS/clean-gradle-cache
  
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
  
jobs:
  exclude:
    - <<: *reference_build
      stage: test
  include:
    - <<: *reference_build
      stage: base
      script:
        - travis_retry ./gradlew clean check

script:
  - travis_retry ./gradlew clean check
  
notifications:
  email:
    on_success: never
    recipients:
      - lorenzo.simoncini2@studio.unibo.it